name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Debugging step to list files in the repository
      - name: List files to verify structure
        run: |
          echo "Listing files in the repository"
          ls -R /home/runner/work/swt-ws24-25/swt-ws24-25/

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/swt-ws24-25/homework-7/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests -f swt-ws24-25/homework-7/pom.xml

      - name: Run tests
        run: mvn test -f swt-ws24-25/homework-7/pom.xml

      - name: Generate JaCoCo report
        run: mvn jacoco:report -f swt-ws24-25/homework-7/pom.xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: swt-ws24-25/homework-7/target/site/jacoco
